# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c2597ceb7d013ef71deb2dc2e204a491e01f1edd4faf30abf5b3794b8640da52ddcaf81e4a5e5ed1d3b8815421aa76781e8ec67a05db32126b8f363fc6b2f0

test:
  secret_key_base: 7f165696d8ca79ee0b382b0940ba8ccdef8ea0d6f5220aff90bcf10d1bd95c7956d2a06dac65fb7b5143c15cd6287fccd926e2b03184fcb81502f45ffaf67b05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
